...
jobs:
  build:
    name: Build and Push the image
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.username }}
        password: ${{ secrets.GITOPS }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: akadirvel1/gitops:${{ github.sha }} , akadirvela/gitops:latest
